### ISSUE TITLE
Multiple H1s on Page Due to Articles

### ISSUE THREAD

**Issue by nox7** [codesupport/website-frontend#127]
Due to articles using MD, there is an obvious contextual disconnect between what is in the MD and what is actually rendered on the page. An article can container a markdown heading level 1, but the page itself is rendered with an H1 as the article title.

Duplicate H1s are not allowed in standard web documents and cause crawlers to be confused as to the outline title of a page's document.

E.g.: https://github.com/codesupport/website-frontend/blob/master/src/data/articles/automatic-watering-system-with-a-raspberry-pi.md

The markdown should be parsed down to shift all headers down one level, or articles should be edited and then instructed to not use the heading level 1.

**Comment by LamboCreeper** [comment]
I think it makes sense to shift down headings in articles down a level
