### ISSUE TITLE
Share Buttons Are Not Correctly Aligned

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/website-frontend#136]
The share buttons are not correctly aligned: the text is left-aligned, but should be centre-aligned.

This is taken from Safari on an iPhone 14 Pro.

 ![image](https://github.com/codesupport/website-frontend/assets/12111454/3201802a-e8b8-49b4-aa49-d51e74b5292e)

**Comment by Edberaga** [comment]
It is alligned center, just need to short the padding at mobile size.

I change the padding from 13px 30px into 13px 10px. It appears well-alligned like this:
![image](https://github.com/codesupport/website-frontend/assets/72023119/b25b459b-401c-4466-973f-e13b77bc6790)
