### ISSUE TITLE
GitHub issue Templates Integration

### ISSUE THREAD

**Issue by Bashamega** [codesupport/website-frontend#139]
Hello:)

I think GitHub issues templates will be a great addition, and also it will help new people to know how to create a good issue.

I would like to work on this issue

**Comment by LamboCreeper** [comment]
Hi,

Feel free to copy over our [standard issue templates](https://github.com/codesupport/code-review-tool/tree/master/.github/ISSUE_TEMPLATE) across to this repository. You'll just need to tweak some naming.

Thanks!
