### ISSUE TITLE
UI bug: Missing padding

### ISSUE THREAD

**Issue by Bashamega** [codesupport/website-frontend#147]
I think there should be a padding right and left on the blog post grid
![image](https://github.com/user-attachments/assets/ada2e49e-f066-410d-8ed7-b55774262f41)
I would like to work on this

**Comment by LamboCreeper** [comment]
I am unable to reproduce this on either Safari or Firefox: I have padding each side. Which browser are you using?

**Comment by LamboCreeper** [comment]
Appears to be [reproducible](https://discord.com/channels/240880736851329024/720675421837983854/1281723139365142568) - yep feel free to fix.
