### ISSUE TITLE
Resources are not in alphabetical order

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/website-frontend#16]
Currently, on the [resources page](https://codesupport.dev/resources) the cards are not ordered alphabetically, but instead by category order. This should be changed so that they are in alphabetical order as it makes it seem that we only have resources of X category until you scroll down (or filter).

#### Expected
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/12111454/89739504-297a4b80-da79-11ea-8379-a3d3a5c15400.png">

#### Actual
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/12111454/89739507-326b1d00-da79-11ea-80f1-21a167f733d6.png">

**Comment by olivier-b-be** [comment]
On it
