### ISSUE TITLE
Article Metadata Cover Image

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/website-frontend#47]
**As a** article author
**I want to** my cover image to show in the metadata
**So that** embeds of my article are more appealing 

Articles have the ability to have a cover image stored against them, although we do not currently take advantage of this. We should take this data and use it to:
- Set a large metadata image for embeds
- Set on the rich data for search results

**Comment by ajsaraujo** [comment]
Gonna give this a try.

**Comment by LamboCreeper** [comment]
Closing as no longer supported by the new API
