### ISSUE TITLE
Navigation bar spacing gets messed up when you try to visit CMS.

### ISSUE THREAD

**Issue by Salint** [codesupport/website-frontend#67]
If you manually go to `https://codesupport.dev/cms` where you don't have access...
There is a slight shadow under the navigation bar...
![image](https://user-images.githubusercontent.com/41103301/136392080-11f6a2f7-149b-4023-a3f9-6c1300af97ad.png)

Once you click the home button however(or any button in the navigation bar), the shadow is still visible and causes a spacing issue.
![image](https://user-images.githubusercontent.com/41103301/136392299-35f0491c-0ac8-449e-80fb-0cbcf4b2ac05.png)

**Comment by LamboCreeper** [comment]
Closing as CMS will be deprecated when new API is released
