### ISSUE TITLE
Profile Page is not Responsive

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/website-frontend#68]
![image](https://user-images.githubusercontent.com/12111454/136432404-f8780da0-1c74-490c-b409-f034ccfa3d28.png)

The layout should be changed on mobile so that articles are first, followed by showcase posts and finally GitHub repositories.

We can hide the avatar or reduce it's size and put the name underneath.

**Comment by Salint** [comment]
Made a pull request.
